#version 450 core

layout(local_size_x = 8, local_size_y = 4, local_size_z = 1) in;

struct PointLight {
    vec3 pos;
    vec3 ambient;
    vec3 diffuse;
    vec3 specular;
    vec3 term;
};

layout (std430, binding = 0) buffer PointLights {
    PointLight pointLights[];
};

layout (std430, binding = 1) buffer RetPointLight {
    PointLight ret_pointLight;
};

void main() {
  ret_pointLight = pointLights[1];  
}
