#version 450 core

layout(local_size_x = 8, local_size_y = 4, local_size_z = 1) in;

struct Triangle {
    vec3 v0;
    vec3 v1;
    vec3 v2;
};

struct BvhNode {
    vec3 aabbMin;
    uint leftFirst;
    vec3 aabbMax;
    uint triCount;
};

layout(std430, binding = 0) buffer BvhNodesIn {
    BvhNode bvhNodes[];
} in_;

layout(std430, binding = 1) buffer BvhNodesOut {
    BvhNode bvhNodes[];
} out_;

void main() {
    vec2 pixel_coords = vec2(gl_GlobalInvocationID.xy);

}
