#version 450 core

layout(local_size_x = 8, local_size_y = 4, local_size_z = 1) in;

struct Triangle {
    vec3 v0;
    vec3 v1;
    vec3 v2;
};

layout(std430, binding = 0) buffer TrianglesIn
{
    Triangle triangles[];
} in_;

layout(std430, binding = 1) buffer TrianglesOut
{
    Triangle triangles[];
} out_;

void main() {
    for (int i = 0; i < in_.triangles.length; i++) {
        out_.triangles[i] = in_.triangles[i];
    }
}
